runtime: nodejs
env: flex

env_variables:
  # --REQUIRED--
  DATABASE_URI: mongodb://sticker:wonderful@ds153652.mlab.com:53652/cyfa-dev
  APP_ID: cy129-asd12
  MASTER_KEY: das091-123aa
  SERVER_URL: https://sticker-dashboard.appspot.com/parse
  AWS_ACCESS_KEY_ID: AKIAIK4H65MXJJMO7Q6A
  AWS_SECRET_ACCESS_KEY: A85CCq3+X8c7pBHg6EOdvIL3YzPuvNyPwG8wvyNK

  # --OPTIONAL--
  # FILE_KEY: <your-file-key>
  # PARSE_MOUNT: /parse
  # CLOUD_CODE_MAIN:  